version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: api_gateway
    ports:
      - "8888:80"
    depends_on:
      - user-service
      - tracking-service
      - frontend
    restart: unless-stopped

  user-service:
    build: ./services/user-service
    container_name: user_service
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_NAME: cargo_db
      DB_PORT: 5432
    depends_on:
      - postgres

  auth-service:
    build: ./services/auth-service
    container_name: auth_service

  tracking-service:
    build: ./services/tracking-service
    container_name: tracking_service
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_NAME: cargo_db
      DB_PORT: 5432
    depends_on:
      - postgres

  update-service:
    build: ./services/update-service
    container_name: update_service
    depends_on:
      - rabbitmq

  notification-service:
    build: ./services/notification-service
    container_name: notification_service
    depends_on:
      - rabbitmq
  
  frontend:
    build: ./frontend
    container_name: frontend_service

  postgres:
    image: postgres:13-alpine
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cargo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/

  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:9.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  postgres_data:
  rabbitmq_data:
  grafana_data: