global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user_service:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth_service:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'tracking-service'
    static_configs:
      - targets: ['tracking_service:3002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'update-service'
    static_configs:
      - targets: ['update_service:3003']
    metrics_path: '/metrics'
    scrape_interval: 10s

